[env]
RUNEWIDTH_EASTASIAN = "0"

[colors.bright]
black = "0x56afa0"
blue = "0x87c9e5"
cyan = "0x56afa0"
green = "0x56afa0"
magenta = "0xcea7de"
red = "0xcd909b"
white = "0xd6d6d6"
yellow = "0xe2aea2"

[colors.normal]
black = "0x56afa0"
blue = "0x87c9e5"
cyan = "0x78b6ad"
green = "0x56afa0"
magenta = "0xcea7de"
red = "0xcd909b"
white = "0xcbcdcd"
yellow = "0xe2aea2"

[colors.primary]
background = "0x222529"
foreground = "0xd6d6d6"

[font]
size = 15.0

[font.bold]
family = "Sauce Code Pro Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Sauce Code Pro Nerd Font"
style = "Bold Italic"

[font.italic]
family = "Sauce Code Pro Nerd Font"
style = "Italic"

[font.normal]
family = "Sauce Code Pro Nerd Font"
style = "Regular"

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Right"

[selection]
save_to_clipboard = true

[window]
opacity = 0.8
